language: php

sudo: false

checks:
    php:
        code_rating: true
        duplication: true

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - 7.1

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*
        - php: 5.6
          env: SYMFONY_VERSION=3.*
        - php: 7.0
          env: SYMFONY_VERSION=2.7.*
        - php: 7.0
          env: SYMFONY_VERSION=3.*
        - php: 7.1
          env: SYMFONY_VERSION=2.7.*
        - php: 7.1
          env: SYMFONY_VERSION=3.*

env:
    global:
        - deps=no

install:
    - composer install

script:
    - vendor/bin/phpspec run
