imports:
    - { resource: config.yml }

swiftmailer:
    transport: mindbaz
    id_site:   '%mindbaz_id_site%'
    username:  '%mindbaz_login%'
    password:  '%mindbaz_password%'
    campaigns: '%mindbaz_campaigns%'
