imports:
    - { resource: parameters.yml }

framework:
    secret:      MindbazBundle
    serializer:  ~
    test:        ~
    profiler:
        collect: false

monolog:
    handlers:
        file_log:
            type: stream
            path: '%kernel.logs_dir%/mindbaz.log'
